CREATE TABLE  IF NOT EXISTS `USER_DETAIL`(
	`ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `FirstName` VARCHAR(100) NOT NULL,
    `LastName` VARCHAR(100) NOT NULL
);

CREATE TABLE  IF NOT EXISTS USER(
	`Password` VARCHAR(45),
	`ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `Email` VARCHAR(100) NOT NULL,
    `DETAIL` INT REFERENCES USER_DETAIL(`ID`)
);
CREATE TABLE IF NOT EXISTS `USER_ROLES` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `UserID` INT NOT NULL,
  `Role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY (Role,UserID),
  KEY (UserID),
  CONSTRAINT FOREIGN KEY (UserID) REFERENCES USER (ID));